language: python
sudo: required
dist: trusty
cache:
  directories:
    - eggs
    - .npm
notifications:
  slack:
    secure: hlTj34WpuzQmsyxnUnFEwlAJeDcElshGfgw7oHuicAD83LorBFTc9ap6FhZXI5LFnqEl28FZ9YkJJRl0tFZgaApllrMmNCeK2FfRjnF8XGz2JS6Iiyj+hgWrKHHIbcS2g5R6L2/uzIhdMvCb97cReZckjo9lumYAdXGHY8DJbik=
addons:
  apt:
    packages:
      - oracle-java8-set-default
      - bsdtar
      - graphviz
env:
  global:
    - secure: |-
        OaH6diFXibRmQv6Xeww7RVj5w+fn0XjWyEJfP/vJclNDnLG+j2WvOdaq6Q34RU/lgrZacCIEqDKjJHS18LIod8eKLorNwpEdM2Q196QKKmXOIDCOLQCU7MZpETUWI07rpbSe4giMtSm9lYlGTjZ1hnAO/otSJ8qyJJnEw+HVf2UusuEKVorc1D2+p9/q4dgkzjTuPYF94IHBXci9a+8G3DuiNwZ2nwFm4hmeyTnU8oCxtc10UcsUbjsUiJHKTZrDe/i/mc5zzFTtoC4j7A0KT1scyDs2w42Vxp4nDZOrJ/YQgy6EdU05/KldET1KtFWAkJHzOqqzIiIsJVhKDhUWTcnlidU12OLvnu4Q55dtv/jmDvz+HvjSKsBNEmvGf6Fk09C5c3GGQzzHC1KLwBAVvkl6crM9oTv8xz1vVkTSyzw54s8mGyC7CR0iIUlTFhR2uqbuRUbxQb5ozXZT8yxXvgSB629q2gBec9X5lmA3mxXj1RknV/tR3RZNZLouzp5Haog5ZHZvee4JEu/vn1WAxHwMJCPeTUajc+nk9+hzP4GjGUtG9fkChIIJ60cZzA4RQm8TGuS8foXBKqVzufC59hBEj5MP53CFb8VlSqimYoYbOoR6sTl+bnQniMJ3uejh//ifUQapcEi5quiPo+ypGhtljxU9R6Rm1TcWyftSjmw=
    - secure: |-
        L8ACkdNWn1dg8GzEpJUbyKuEW+Ovek8bq8/sy//NySxh79UnXwcrU1Z2INmsnx16F7xKA1UuIRMeGciKq7N603QrPhNxZ/r4f1R4ifryFkiZcnpFBw+X5iXNByAY1gHDdm8ZlINE9ST/yEZLV7IbBkg5LSHElKCPG+Ncww8EAC0QJWnn34D6YiROjdc+WfRgyQyiktP7s8VwYuHm/XugydTjGxr6B4Jt8l9Edm/WuOlj3U98ioRG2ZSXUYNHdkf5uCeOADujbjvhAfPZq0uHWf22Mmh0Q5fL8H9dRayiZcIik03VNpDV1+20Urjz55GuUILikRzquavp0uATDeqi9sGvUbjnCeOuNnWfNnw7FjFTjO8/yqce/VlOYWsoFSE4sTFgIDr+k/lx28pYftHcfLq96KRdppEcrOagwQSHpKCRgJ1HetJWmF0YBU054bZFdPy7BlI3ixtEhSJQCOPCZ0vf4rd5OyzE2/uhEmC/9D8gbXdfYySDRLAIEIzwgZQr0xLQhDLK2HJYqRsKEz3FqR29JfAqAWxtYgKBEy4tPj8GJclh4xoFV+V4FbVN557HbMa8Pm21pza1XamfUSZ1pwHIWCJoRQ/kqRC2vKWwkHPT5jFTXQypvLUrNs88zluDK2Bzlu5mUO8iVxyS1xMHaXrsrFcMFUA+Hu4d/tebcpA=
    - BOTO_CONFIG=tmp/bogusvalue
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - ES_VERSION=5.6.1
    - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.deb
    - PATH="/usr/share/elasticsearch/bin:/usr/lib/postgresql/9.3/bin:$PATH"
    - ES_JAVA_OPTS="-Xms2g -Xmx2g"
matrix:
  include:
    - python: "3.4.3"
      env: BROWSER=Chrome
    - python: "3.4.3"
      env: BROWSER=
before_install:
  - postgres --version
  - initdb --version
  - nvm install 10
  - node --version
  - npm config set python /usr/bin/python2.7
  - curl -O  ${ES_DOWNLOAD_URL} && sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}.deb && sudo service elasticsearch stop
  - pip install -U zc.buildout setuptools
install:
  - buildout bootstrap
  - bin/buildout -c buildout-travis.cfg || (echo "Retrying buildout" && bin/buildout -c buildout-travis.cfg)
  - sudo chown -R travis /etc/elasticsearch
before_script:
  - >
    if test -n "$BROWSER"; then
      CONNECT_URL=https://saucelabs.com/downloads/sc-4.4.5-linux.tar.gz
      CONNECT_DOWNLOAD=sc.tar.gz
      SC_READYFILE=sauce-connect-ready-$RANDOM
      SC_LOGFILE=$HOME/sauce-connect.log
      SC_PIDFILE=$HOME/sauce-connect.pid
      curl $CONNECT_URL > $CONNECT_DOWNLOAD
      mkdir sc
      tar -zxf $CONNECT_DOWNLOAD --strip 1 --directory sc
      sc/bin/sc --readyfile $SC_READYFILE \
        --logfile $SC_LOGFILE \
        --pidfile $SC_PIDFILE \
        --tunnel-identifier $TRAVIS_JOB_NUMBER \
        --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY > /dev/null &
      while test -f "$SC_PIDFILE" && test ! -f "$SC_READYFILE"; do sleep .5; done
    fi
script:
  - if test -z "$BROWSER"; then npm test; fi
  - if test -z "$BROWSER"; then bin/test -v -v --timeout=400 -m "not bdd"; fi
  - >
    if test -n "$BROWSER"; then
      test -f "$SC_PIDFILE" && bin/test -v -v --timeout=400 -m "bdd" --tb=short \
        --splinter-implicit-wait 10 \
        --splinter-webdriver remote \
        --splinter-remote-url "http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@localhost:4445/wd/hub" \
        --splinter-socket-timeout 300 \
        --browser-arg tunnel-identifier "$TRAVIS_JOB_NUMBER" \
        --browser-arg-int build  "$TRAVIS_BUILD_NUMBER" \
        --browser-arg-int idleTimeout 300 \
        --browser-arg name "$TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_COMMIT" \
        --browser-arg browser "$BROWSER" \
        --browser-arg platform "Linux"
    fi
after_script:
  - >
    if test -f "$SC_PIDFILE"; then
      SAUCE_JOB_ID=`grep -m 1 /session/ "$HOME/sauce-connect.log" | cut -d / -f 7`
      SAUCE_PASSED=`((TRAVIS_TEST_RESULT == 0)) && echo true || echo false`
      curl -H "Content-Type:text/json" -s -X PUT -d "{\"passed\": $SAUCE_PASSED}" \
        "http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@saucelabs.com/rest/v1/$SAUCE_USERNAME/jobs/$SAUCE_JOB_ID" > /dev/null
      echo "Sauce test page https://saucelabs.com/tests/$SAUCE_JOB_ID"
      kill $(cat "$SC_PIDFILE")
      wait $(cat "$SC_PIDFILE")
    fi
