version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:10.24.1
    working_directory: ~/regulome-encoded

jobs:
  npm:
    executor: node
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Install Javascript packages and build
          command: npm ci
      - run:
          name: npm tests
          # Can't store test results, the CLI for our Jest version doesn't support --ci or --reporter flags
          command: npm run circleci-test

workflows:
  version: 2
  regulome-encoded-tests:
    jobs:
      - npm
