version: 2.1

workflows:
  version: 2
  regulome-encoded-tests:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: medium
    working_directory: ~/regulome-encoded
    steps:
      - checkout
      - run:
          name: Build docker images
          command: docker-compose build 
      - run:
          name: npm tests
          # Can't store test results, the CLI for our Jest version doesn't support --ci or --reporter flags
          command: docker-compose run regulome npm run circleci-test
